variables:
  PIPELINE_RUNNER: registry.gitlab.com/darklab2/darklab_pipeliner/darklab-pipeliner:kubectl-v1.0.3
  terraform_image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest

stages:
  - testing
  - terraform-prod
  - deploy-prod

testing:
  image: ${PIPELINE_RUNNER}
  stage: testing
  script:
    - echo 123456

terraform_prod:
  image: ${terraform_image}
  stage: terraform-prod
  script:
    - cd terraform/cluster
    - gitlab-terraform init
    - gitlab-terraform plan
    - gitlab-terraform plan-json
    - gitlab-terraform apply
  rules:
    - when: manual
  variables:
    TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/cluster
    TV_VAR_hcloud_token: $hcloud_token

prod_init_kube:
  image: ${PIPELINE_RUNNER}
  stage: deploy-prod
  script:
    - mkdir ~/.kube
    - echo "${kubectl_config}" > ~/.kube/config
    - cd ansible
    - python3 install_cluster.py
  needs:
    - terraform_prod